FROM eclipse-temurin:17-jdk-alpine
COPY Main.java /src/Main.java 
#RUN javac Main.java
CMD ["java", "Main"]
# TODO:  Add the compiled java (aka bytecode, aka .class)
# TODO: Run the Java with: “java Main” command.
